[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.distutils.egg_info]
egg_base = "."

[project]
name = "CardiologyGenAI-AgenticRAG"
version = "0.1.0"
description = "Agent-based RAG framework for cardiology protocols"
requires-python = ">=3.11,<3.13"
authors = [
    { name = "Christian Faccio", email = "christian.faccio@studenti.units.it" },
    { name = "Gaia Saveri", email = "gaia.saveri@gmail.com" }
]

dependencies = [
    "pydantic==2.11.7",
    "qdrant-client==1.15.1",
    "langchain>=1.0.0",
    "langchain-core>=1.0.0",
    "langgraph>=1.0.0",
    "langgraph-checkpoint-postgres==2.0.23",
    "langchain-ollama>=1.0.0",
    "langchain-huggingface>=1.0.0",
    "langchain-community>=0.4.1",
    "langchain-qdrant>=1.0.0",
    "langchain-classic>=1.0.0",
    "sentence-transformers==5.1.0",
    "faiss-cpu==1.12.0",
    "fastembed==0.7.2",
    "sqlalchemy==2.0.43",
    "psycopg[binary]==3.3.1",
    "asyncpg==0.30.0",
    "transformers==4.56.0",
    "bitsandbytes==0.42.0",
    "accelerate==1.10.1",
    "safetensors>=0.4.3",
    "pwdlib[argon2]==0.3.0",
    "PyJWT==2.10.0",
    "fastapi[standard]==0.116.2",
    "cardiologygenai-coordo @ git+https://github.com/cardiology-gen-ai/cardiology-gen-ai.git@main"
]

[project.optional-dependencies]
documentation = [
    "sphinx==7.3.7",
    "sphinxcontrib-mermaid==1.0.0",
    "autodoc-pydantic==2.2.0",
    "sphinx-toolbox==4.0.0",
    "sphinx-book-theme==1.1.4"
]

prompting = [
    "dspy==3.0.4"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["agentic_rag*"]

[tool.setuptools.package-data]
"agentic_rag.agent.prompts" = ["*.yaml"]