filename_title_mapping = {
    "Peripheral_Arterial_&_Aortic_Diseases_2024": "2024 ESC Guidelines for the management of peripheral arterial and aortic disease",
    "Acute_Coronary_Syndromes_(ACS)_2023": "2023 ESC Guidelines for the management of acute coronary syndromes",
    "Ventricular_Arrhythmias_and _the_Prevention_of_Sudden_Cardiac_Death_2022": "2022 ESC Guidelines for the management of patients with ventricular arrhythmias and the prevention of sudden cardiac death",
    "Cardiomyopathies_2023": "2023 ESC Guidelines for the management of cardiomyopathies",
    "Chronic_Coronary_Syndromes_2024": "2024 ESC Guidelines for the management of chronic coronary syndromes",
    "Elevated_Blood_Pressure_and_Hypertension_2024": "2024 ESC Guidelines for the management of elevated blood pressure and hypertension",
    "Cardio-oncology_2022": "2022 ESC Guidelines on cardio-oncology developed in collaboration with the European Hematology Association (EHA), the European Society for Therapeutic Radiology and Oncology (ESTRO) and the International Cardio-Oncology Society (IC-OS)",
    "Atrial_Fibrillation_2024": "2024 ESC Guidelines for the management of atrial fibrillation developed in collaboration with the European Association for Cardio-Thoracic Surgery (EACTS)",
    "Non-Cardiac Surgery- Cardiovascular_Assessment_and_Management_2022": "2022 ESC Guidelines on cardiovascular assessment and management of patients undergoing non-cardiac surgery",
    "CVD_and_Diabetes_2023": "2023 ESC Guidelines for the management of cardiovascular disease in patients with diabetes",
    "Pulmonary_Hypertension_2022": "2022 ESC/ERS Guidelines for the diagnosis and treatment of pulmonary hypertension",
    "CVD_Prevention_2021": "2021 ESC Guidelines on cardiovascular disease prevention in clinical practice",
    "Endocarditis_2023": "2023 ESC Guidelines for the management of endocarditis",
    "Heart_Failure_2021": "2021 ESC Guidelines for the diagnosis and treatment of acute and chronic heart failure",
    "Sports_Cardiology_and_Exercise_in_Patients_with_CVD_2020": "2020 ESC Guidelines on sports cardiology and exercise in patients with cardiovascular disease",
    "Cardiac_Pacing_&_CRT_2021": "2021 ESC Guidelines on cardiac pacing and cardiac resynchronization therapy",
    "ESC_EACTS_Myocardial_Revascularization_2018": "2018 ESC/EACTS Guidelines on myocardial revascularization",
    "Syncope_2018": "2018 ESC Guidelines for the diagnosis and management of syncope",
    "Adult_Congenital_Heart_Disease_2020": "2020 ESC Guidelines for the management of adult congenital heart disease",
    "Supraventricular_Tachycardia_2019": "2019 ESC Guidelines for the management of patients with supraventricular tachycardia",
    "Cardiovascular_Diseases_during_Pregnancy_2018": "2018 ESC Guidelines for the management of cardiovascular diseases during pregnancy",
    "Valvular_Heart_Disease_2021": "2021 ESC/EACTS Guidelines for the management of valvular heart disease",
    "Pericardial_Disease_2018": "2015 ESC Guidelines for the diagnosis and management of pericardial diseases",
    "Dyslipidaemias_2019": "2019 ESC/EAS Guidelines for the management of dyslipidaemias: lipid modification to reduce cardiovascular risk",
    "Acute_Pulmonary_Embolism_2019": "2019 ESC Guidelines for the diagnosis and management of acute pulmonary embolism developed in collaboration with the European Respiratory Society (ERS)",
    "Fourth_Universal_Definition_of_Myocardial_Infarction_2018": "Fourth universal definition of myocardial infarction (2018)",
    "Focused_Update_on_Heart_Failure_2023": "2023 Focused Update of the 2021 ESC Guidelines for the diagnosis and treatment of acute and chronic heart failure",
}