# import os
from typing import List, Tuple

import dspy

# from agentic_rag.config.manager import LLMProvider
# from agentic_rag.config.manager import AgentConfigManager
from agentic_rag.agent import output

# config = AgentConfigManager(
#     app_id=os.getenv("AGENT_ID"), config_path=os.getenv("CONFIG_PATH")
# ).config
# lm_config = config.llm
#
# if lm_config.provider.value == LLMProvider.ollama.value:
#     lm = dspy.LM(
#         f"ollama_chat/{lm_config.model_name}",
#         api_base="http://localhost:11434",
#         api_key="",
#     )
# else:
#     lm = dspy.LM(
#         f"huggingface/{lm_config.model_name}",
#         quantization=f"{lm_config.nbits}bit" if lm_config.nbits < 16 else None,
#         # device="cuda",
#     )
# dspy.configure(lm=lm, adapter=dspy.JSONAdapter())

node_names = {
    "contextualize_question": "ContextualizeQuestion",
    "conversational_agent": "ConversationalAgent",
    "error_handler_node": "ErrorHandler",
    "generate": "Generate",
    "generate_default_response": "GenerateDefaultResponse",
    "generate_document_response": "GenerateDocumentResponse",
    "question_rewriter": "QuestionRewriter",
    "detect_language": "DetectedLanguage",
    "document_request_detector": "DocumentRequestDetector",
    "router": "Router",
    "answer_grader": "AnswerGrader",
    "ground_validator": "GroundValidator",
    "retrieval_grader": "RetrievalGrader",

    "ambiguity_detector": "AmbiguityDetector",
    "question_clarifier": "QuestionClarifier",
    "hyde": "HyDe",
}


class ContextualizeQuestion(dspy.Signature):  # test
    system_prompt_context: str = dspy.InputField(desc="Background information about the situation or task, including relevant domain, "
                                        "purpose, and constraints to guide the query rewriting.")
    question: str = dspy.InputField(desc="The original user query.")
    history: List[Tuple[str, str]] = dspy.InputField(desc="List of previous messages in conversation.")
    language: str = dspy.InputField(desc="Language that should be used in the conversation.")
    contextualized_query: str = dspy.OutputField(dec="Question rewritten to be self-contained, without needing conversation history.")


class ConversationalAgent(dspy.Signature):
    agent_prompt: str = dspy.InputField(desc="Background information about the persona of the agent and its role, "
                                        "to guide question answering")
    question: str = dspy.InputField(desc="User query.")  # contextualized
    history: List[str] = dspy.InputField(desc="List of previous messages in conversation")
    response: str = dspy.OutputField(desc="Answer to user question")


class AmbiguityDetector(dspy.Signature):
    system_prompt_context: str = dspy.InputField(
        desc="Background information about the situation or task, including relevant domain, "
             "purpose, and constraints to guide the query rewriting.")
    contextual_question: str = dspy.InputField(desc="User query.")


class QuestionClarifier(dspy.Signature):
    system_prompt_context: str = dspy.InputField(
        desc="Background information about the situation or task, including relevant domain, "
             "purpose, and constraints to guide the query rewriting.")
    language: str = dspy.InputField(desc="Language that should be used in the conversation.")
    contextual_question: str = dspy.InputField(desc="User query.")
    ambiguity_reasons: List[str] = dspy.InputField(desc="List of reasons why the query is considered ambiguous")


class HyDe(dspy.Signature):
    contextual_question: str = dspy.InputField(desc="User query.")


class MultiQueryGenerator(dspy.Signature):
    contextual_question: str = dspy.InputField(desc="User query.")


class ErrorHandler(dspy.Signature):
    error_message: str = dspy.InputField(desc="Original error message generated by the program.")
    error_explanation: str = dspy.OutputField(desc="User-friendly and helpful explanation of the error message.")


class Generate(dspy.Signature):  # test (maybe feedback can be used here)
    documents: List[str] = dspy.InputField(desc="List of retrieved context.")
    question: str = dspy.InputField(desc="User query.")
    response: str = dspy.OutputField()


class GenerateDefaultResponse(dspy.Signature):
    question: str = dspy.InputField(desc="User query.")
    response: str = dspy.OutputField()


class GenerateDocumentResponse(dspy.Signature):
    question: str = dspy.InputField(desc="User query.")
    documents: str = dspy.InputField(desc="List of documents requested by the user.")
    response: str = dspy.OutputField()


class QuestionRewriter(dspy.Signature):  # test (maybe in module)
    question: str = dspy.InputField(desc="The original user query.")
    improved_question: str = dspy.OutputField(desc="Question rewritten to be optimized for vectorstore retrieval.")


class DetectLanguage(dspy.Signature):
    question: str = dspy.InputField(desc="User query.")
    language: output.DetectedLanguage = dspy.OutputField()


class DocumentRequestDetector(dspy.Signature):  # test
    question: str = dspy.InputField(desc="User query.")  # contextualized
    document_request: output.DocumentRequest = dspy.OutputField()


class RetrieveRouter(dspy.Signature):  # test
    question: str = dspy.InputField(desc="User query.")  # contextualized
    vector_db_description: str = dspy.InputField(desc="Description of the vectorstore containing documents you can access.")  #  vector_db_description
    route: output.RouteQuery = dspy.OutputField()


class AnswerGrader(dspy.Signature): # TODO: this can be aligned with user feedback
    question: str = dspy.InputField(desc="User query.")  # check both original and contextualized
    response: str = dspy.InputField(desc="Answer given to the user question.")
    answer_grade: output.GradeAnswer = dspy.OutputField()


class GroundValidator(dspy.Signature):  # TODO: this is a sort of faithfulness
    documents: List[str] = dspy.InputField(desc="Pieces of retrieved text over which the answer must be grounded.")
    response: str = dspy.InputField(desc="Answer given to the user question.")
    groundedness: output.GradeGrounding = dspy.OutputField()


class RetrievalGrader(dspy.Signature):
    question: str = dspy.InputField(desc="User query.")
    document_filenames: List[str] = dspy.InputField(desc="Name of the retrieved documents.")
    documents: List[str] = dspy.InputField(desc="Pieces of retrieved text over which the answer must be grounded.")
    document_relevance: output.GradeDocuments = dspy.OutputField()

# TODO: maybe useful for testing sub-graphs

# class Hop(dspy.Module):
#     def __init__(self, num_docs=10, num_hops=4):
#         self.num_docs, self.num_hops = num_docs, num_hops
#         self.generate_query = dspy.ChainOfThought('claim, notes -> query')
#         self.append_notes = dspy.ChainOfThought('claim, notes, context -> new_notes: list[str], titles: list[str]')
#
#     def forward(self, claim: str) -> list[str]:
#         notes = []
#         titles = []
#
#         for _ in range(self.num_hops):
#             query = self.generate_query(claim=claim, notes=notes).query
#             context = search(query, k=self.num_docs)
#             prediction = self.append_notes(claim=claim, notes=notes, context=context)
#             notes.extend(prediction.new_notes)
#             titles.extend(prediction.titles)
#
#         return dspy.Prediction(notes=notes, titles=list(set(titles)))

